import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "my little discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="./sign-in">
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html> 
    </ClerkProvider>
  );
}
