import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import { QueryClient } from "@tanstack/react-query";
import { QueryProvider } from "@/components/providers/query-provider";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "my little discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="./sign-in">
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            storageKey="discord-theme"
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >

            <SocketProvider>
              <ModalProvider />
              <QueryProvider>
              {children}
              </QueryProvider>
           
            </SocketProvider>

          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
} 
